@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

FoodBook *-right-> "1" UniquePersonList
FoodBook *-right-> "1" UniqueDeliveryList
UniqueDeliveryList -[hidden]down- UniquePersonList
UniqueDeliveryList -[hidden]down- UniquePersonList

UniqueDeliveryList -right-> "*" Delivery
UniquePersonList -right-> "*" Person

Delivery *--> "1" Integer
Delivery --> "1" Person
Delivery *--> "1" DateTime


Person ---> "*" Tag

Person *--> "1" Name
Person *--> "1" Phone
Person *--> "1" Email
Person *--> "1" Address


@enduml
